/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.awt.Dimension;
import java.io.File;
import java.nio.file.Path;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Cores;
import model.FileManager;
import model.Instruction;

/**
 *
 * @author rayn0
 */
public class main extends javax.swing.JFrame {
    private int panellocationY = 30;
    private int panelSize = 250;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Asm files", "asm");//define el formato de archivo que se permite cargar en el file chooser
    private ArrayList<File> fileList = new ArrayList<File>();
    private ArrayList<String> execute = new ArrayList<String>();
    private ArrayList<Integer> config = new ArrayList<>();
    private DefaultListModel<String> modelMemory = new DefaultListModel<>();
    private DefaultListModel<String> modelDisk = new DefaultListModel<>();
    private int memorySize = 0;
    private int diskSize = 0;
    /**
     * Creates new form main
     */
    public main(ArrayList<Instruction> config,int memSize,int sizeDisk) {
        initComponents();
        config = config;
        this.memorySize = memSize;
        this.diskSize = sizeDisk;
    }

    private main() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        console = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        PanelPBC = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PBCTable = new javax.swing.JTable();
        lblBPC = new javax.swing.JLabel();
        panelDisk = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diskList = new javax.swing.JList<>();
        panelMemory = new javax.swing.JPanel();
        memoryTable = new javax.swing.JScrollPane();
        instructionList = new javax.swing.JList<>();
        lblMemory = new javax.swing.JLabel();
        panelWork1 = new javax.swing.JScrollPane();
        workQueue1 = new javax.swing.JTable();
        panelWork2 = new javax.swing.JScrollPane();
        workQueue = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        panelN1 = new javax.swing.JScrollPane();
        n1Table = new javax.swing.JTable();
        panelN2 = new javax.swing.JScrollPane();
        n1Table1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtLoad = new javax.swing.JTextField();
        btnLoadFile = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        lblConsole = new javax.swing.JLabel();
        lblDisk = new javax.swing.JLabel();
        panelFiles = new javax.swing.JScrollPane();
        fileTable = new javax.swing.JTable();
        lblFiles = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        console.setBackground(new java.awt.Color(255, 255, 255));
        console.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        console.setViewportBorder(javax.swing.BorderFactory.createCompoundBorder());
        console.setAutoscrolls(true);

        txtConsole.setColumns(20);
        txtConsole.setForeground(new java.awt.Color(153, 153, 153));
        txtConsole.setRows(5);
        txtConsole.setText(">");
        txtConsole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        txtConsole.setOpaque(false);
        console.setViewportView(txtConsole);

        getContentPane().add(console, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 450, 140));

        PBCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "File", "PC", "IR", "AC", "AX", "BX", "CX", "DX", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PBCTable.setOpaque(false);
        PBCTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(PBCTable);
        if (PBCTable.getColumnModel().getColumnCount() > 0) {
            PBCTable.getColumnModel().getColumn(0).setResizable(false);
            PBCTable.getColumnModel().getColumn(1).setResizable(false);
            PBCTable.getColumnModel().getColumn(2).setResizable(false);
            PBCTable.getColumnModel().getColumn(3).setResizable(false);
            PBCTable.getColumnModel().getColumn(4).setResizable(false);
            PBCTable.getColumnModel().getColumn(5).setResizable(false);
            PBCTable.getColumnModel().getColumn(6).setResizable(false);
            PBCTable.getColumnModel().getColumn(7).setResizable(false);
            PBCTable.getColumnModel().getColumn(8).setResizable(false);
        }

        lblBPC.setForeground(new java.awt.Color(255, 255, 255));
        lblBPC.setText("BPC'S");

        javax.swing.GroupLayout PanelPBCLayout = new javax.swing.GroupLayout(PanelPBC);
        PanelPBC.setLayout(PanelPBCLayout);
        PanelPBCLayout.setHorizontalGroup(
            PanelPBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPBCLayout.createSequentialGroup()
                .addComponent(lblBPC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        PanelPBCLayout.setVerticalGroup(
            PanelPBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPBCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBPC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelPBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 440, 230));

        panelDisk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jScrollPane3.setViewportView(diskList);

        javax.swing.GroupLayout panelDiskLayout = new javax.swing.GroupLayout(panelDisk);
        panelDisk.setLayout(panelDiskLayout);
        panelDiskLayout.setHorizontalGroup(
            panelDiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        panelDiskLayout.setVerticalGroup(
            panelDiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        getContentPane().add(panelDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 570, 180));

        panelMemory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        memoryTable.setBackground(new java.awt.Color(0, 0, 0));
        memoryTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        memoryTable.setViewportView(instructionList);

        javax.swing.GroupLayout panelMemoryLayout = new javax.swing.GroupLayout(panelMemory);
        panelMemory.setLayout(panelMemoryLayout);
        panelMemoryLayout.setHorizontalGroup(
            panelMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memoryTable, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        panelMemoryLayout.setVerticalGroup(
            panelMemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memoryTable, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        getContentPane().add(panelMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, 460, 270));

        lblMemory.setForeground(new java.awt.Color(255, 255, 255));
        lblMemory.setText("Memory");
        getContentPane().add(lblMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 110, -1));

        workQueue1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Instruction", "Value", "File"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workQueue1.getTableHeader().setReorderingAllowed(false);
        panelWork1.setViewportView(workQueue1);
        if (workQueue1.getColumnModel().getColumnCount() > 0) {
            workQueue1.getColumnModel().getColumn(0).setResizable(false);
            workQueue1.getColumnModel().getColumn(1).setResizable(false);
            workQueue1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(panelWork1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 270, 90));

        workQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Instruction", "Value", "File"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workQueue.getTableHeader().setReorderingAllowed(false);
        panelWork2.setViewportView(workQueue);
        if (workQueue.getColumnModel().getColumnCount() > 0) {
            workQueue.getColumnModel().getColumn(0).setResizable(false);
            workQueue.getColumnModel().getColumn(1).setResizable(false);
            workQueue.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(panelWork2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 270, 90));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Work Queue's");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 170, 20));

        n1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Core 2", "Ins", "Ins", "Ins"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        n1Table.getTableHeader().setReorderingAllowed(false);
        panelN1.setViewportView(n1Table);
        if (n1Table.getColumnModel().getColumnCount() > 0) {
            n1Table.getColumnModel().getColumn(0).setResizable(false);
            n1Table.getColumnModel().getColumn(1).setResizable(false);
            n1Table.getColumnModel().getColumn(2).setResizable(false);
            n1Table.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(panelN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 420, -1, 40));

        n1Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Core 1", "Ins", "Ins", "Ins"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        n1Table1.getTableHeader().setReorderingAllowed(false);
        panelN2.setViewportView(n1Table1);
        if (n1Table1.getColumnModel().getColumnCount() > 0) {
            n1Table1.getColumnModel().getColumn(0).setResizable(false);
            n1Table1.getColumnModel().getColumn(1).setResizable(false);
            n1Table1.getColumnModel().getColumn(2).setResizable(false);
            n1Table1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(panelN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, -1, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Core's");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, -1, -1));

        txtLoad.setEditable(false);
        txtLoad.setText("Load File");
        txtLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoadMouseClicked(evt);
            }
        });
        getContentPane().add(txtLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 440, -1));

        btnLoadFile.setBackground(new java.awt.Color(204, 204, 204));
        btnLoadFile.setText("Load");
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 210, -1));

        btnExecute.setText("Execute");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });
        getContentPane().add(btnExecute, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 220, -1));

        lblConsole.setForeground(new java.awt.Color(255, 255, 255));
        lblConsole.setText("Console");
        getContentPane().add(lblConsole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblDisk.setForeground(new java.awt.Color(255, 255, 255));
        lblDisk.setText("Disk");
        getContentPane().add(lblDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Number", "File Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fileTable.getTableHeader().setReorderingAllowed(false);
        panelFiles.setViewportView(fileTable);
        if (fileTable.getColumnModel().getColumnCount() > 0) {
            fileTable.getColumnModel().getColumn(0).setResizable(false);
            fileTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            fileTable.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(panelFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 250, 210));

        lblFiles.setForeground(new java.awt.Color(255, 255, 255));
        lblFiles.setText("Files");
        getContentPane().add(lblFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 70, 20));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 480, -1, -1));

        background.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -90, 1680, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        // TODO add your handling code here:
        if (txtLoad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select a file firts");
        }
        else{
            String [][] none={};
            String titles[] = {"Number","File Name"};
            DefaultTableModel model = new DefaultTableModel(none,titles);
            String files[] = txtLoad.getText().split(",");
            for (int i = 0;i<fileList.size();i++){
                    ArrayList<String> array = new ArrayList<String>();
                    array.add(Integer.toString(i+1));
                    array.add(files[i]);
                    model.addRow(array.toArray());
            }
            fileTable.setModel(model);
            txtLoad.setText("Load File");
        }
            
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void txtLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoadMouseClicked
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileFilter(filter);
        file.setMultiSelectionEnabled(true);
        int option = file.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION){
            File selected[] = file.getSelectedFiles();
            for(File fileSelected:selected){
                fileList.add(fileSelected);
                if(txtLoad.getText().equals("Load File")){
                    txtLoad.setText(""+fileSelected.getName());
                }
                else{
                    txtLoad.setText(txtLoad.getText() + "," +fileSelected.getName());
                }
            }
            
        }
    }//GEN-LAST:event_txtLoadMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        config window = new config();
        window.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    
public static <T> ArrayList<T> merge(Collection<T> a, Collection<T> b) {
    Iterator<T> itA = a.iterator();
    Iterator<T> itB = b.iterator();
    ArrayList<T> result = new ArrayList<T>();

    while (itA.hasNext() || itB.hasNext()) {
        if (itA.hasNext()) result.add(itA.next());
        if (itB.hasNext()) result.add(itB.next());
    }

    return result;
}
    
    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        // TODO add your handling code here:
            int memoryCounter = 0;
            int diskCounter = 0;
            
            ArrayList<FileManager> core1 = new ArrayList<>();
            ArrayList<FileManager> core2 = new ArrayList<>();
            
            int selectedRow[] = fileTable.getSelectedRows();
            
            for(int name:selectedRow){
                execute.add(fileTable.getModel().getValueAt(name,1).toString());
            }
            for (File file:fileList){
                if (execute.contains(file.getName())){
                    FileManager manager = new FileManager(file.toPath());
                    ArrayList<String> instructions = manager.getInstructions();
                    for (String ins:instructions){
                        if (memoryCounter < memorySize && manager.getInstructions().size() < memorySize){
                            memoryCounter++;
                            modelMemory.addElement( memoryCounter+ ". "+manager.getName() + " " + ins);
                            
                        }
                        else{
                            diskCounter++;
                            modelDisk.addElement(diskCounter +". "+ manager.getName() + " " + ins);
                           
                        }
                    }
                    //diviviendo set de instrucciones por nucleo
                    if(manager.getCoreNumber() == 0){
                        core1.add(manager);
                    }
                    else{
                        core2.add(manager);
                    }
                }

            }
            
            ArrayList<ArrayList<String>> core1instruc = new ArrayList<>();
            ArrayList<ArrayList<String>> core2instruc = new ArrayList<>();
            ArrayList<String> core1final = new ArrayList<>();
            ArrayList<String> core2final = new ArrayList<>();
            DefaultTableModel modelCore1 = new DefaultTableModel(new String[] {"Instruction", "Value","File"}, 0);
            DefaultTableModel modelCore2 = new DefaultTableModel(new String[] {"Instruction", "Value","File"}, 0);
            System.out.println("Core 1");
            
            for(int i = 0; i < core1.size(); i++){
                ArrayList<String> temp = new ArrayList<>();
                for(String obj: core1.get(i).getInstructions()){
                    temp.add(obj+"="+core1.get(i).getName());
                }
                core1instruc.add(temp);
            }
            for(int i = 0; i < core2.size(); i++){
                ArrayList<String> temp = new ArrayList<>();
                for(String obj: core2.get(i).getInstructions()){
                    temp.add(obj+"="+core2.get(i).getName());
                }
                core2instruc.add(temp);
            }            
            if(core1.size() > 1){
                Collections.sort(core1instruc, new Comparator<ArrayList<String>>() {    
                    @Override
                    public int compare(ArrayList<String> o1, ArrayList<String> o2) {
                        return (o1.get(0).length() < o2.get(0).length())? 1: -1;
                    }               
                });
            ArrayList<ArrayList<String>> core1merge = new ArrayList<>();
            int cont = 0;
            while(cont < core1instruc.get(0).size()){
                ArrayList<String> temp = new ArrayList<>();
              for(ArrayList<String> obj :core1instruc ){
                 try{
                     temp.add(obj.get(cont));
                    
                 }catch(Exception e){
                 }             
                }
              core1merge.add(temp);
              cont++;
            }
            
            for(ArrayList<String> obj: core1merge){
                core1final.addAll(obj);
            }

            for(String obj: core1final){
                System.out.println(obj);
                String[] out = obj.split("=");
               /* for(String o: out)
                    System.out.println(o);*/
                modelCore1.addRow(new Object[]{out[0]," ",out[1]});
            
            }
            workQueue1.setModel(modelCore1);
            }
            System.out.println(core1final);
            System.out.println();
            System.out.println("Core 2");
            if(core2.size() > 1){
                System.out.println("Linea 1");
                Collections.sort(core2instruc, new Comparator<ArrayList<String>>() {    
                    @Override
                    public int compare(ArrayList<String> o1, ArrayList<String> o2) {
                        return (o1.get(0).length() < o2.get(0).length())? 1: -1;
                    }               
                });
            ArrayList<ArrayList<String>> core2merge = new ArrayList<>();
            int cont1 = 0;
            System.out.println("Linea 2");
            while(cont1 < core2instruc.get(0).size()){
                ArrayList<String> temp = new ArrayList<>();
              for(ArrayList<String> obj :core2instruc ){
                 try{
                     temp.add(obj.get(cont1));
                    
                 }catch(Exception e){
                 }             
                }
              core2merge.add(temp);
              cont1++;
            }
            System.out.println("Linea 3");
            for(ArrayList<String> obj: core2merge){
                core2final.addAll(obj);
            }
            System.out.println(core2final);
            System.out.println("Linea 4");
            core2final.forEach((obj) -> {
                String[] out = obj.split("=");
                modelCore2.addRow(new Object[]{out[0],out[1]});
                });
            System.out.println("Linea 5");
            workQueue.setModel(modelCore2);
            }

            System.out.println(core2final);
            
            diskList.setModel(modelDisk);
            instructionList.setModel(modelMemory);
            
    }//GEN-LAST:event_btnExecuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PBCTable;
    private javax.swing.JPanel PanelPBC;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JScrollPane console;
    private javax.swing.JList<String> diskList;
    private javax.swing.JTable fileTable;
    private javax.swing.JList<String> instructionList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBPC;
    private javax.swing.JLabel lblConsole;
    private javax.swing.JLabel lblDisk;
    private javax.swing.JLabel lblFiles;
    private javax.swing.JLabel lblMemory;
    private javax.swing.JScrollPane memoryTable;
    private javax.swing.JTable n1Table;
    private javax.swing.JTable n1Table1;
    private javax.swing.JPanel panelDisk;
    private javax.swing.JScrollPane panelFiles;
    private javax.swing.JPanel panelMemory;
    private javax.swing.JScrollPane panelN1;
    private javax.swing.JScrollPane panelN2;
    private javax.swing.JScrollPane panelWork1;
    private javax.swing.JScrollPane panelWork2;
    private javax.swing.JTextArea txtConsole;
    private javax.swing.JTextField txtLoad;
    private javax.swing.JTable workQueue;
    private javax.swing.JTable workQueue1;
    // End of variables declaration//GEN-END:variables
}
