/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Instruction;

/**
 *
 * @author rayn0
 */
public class config extends javax.swing.JFrame {
    private ArrayList<Instruction> config = new ArrayList<Instruction>();
    /**
     * Creates new form config
     */
    public config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelConfig = new javax.swing.JScrollPane();
        configTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDisk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMemory = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Settings");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 20));

        configTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        configTable.setForeground(new java.awt.Color(255, 255, 255));
        configTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Load", "2"},
                {"Store", "2"},
                {"Mov", "1"},
                {"Add", "3"},
                {"Sub", "3"},
                {"Inc", "1"},
                {"Dec", "1"},
                {"Int 20H", "0"},
                {"Int 16H", "0"},
                {"Int 05H", "0"},
                {"Jum", "2"},
                {"Cmp", "2"},
                {"Je/Jne", "2"},
                {"Pop", "1"},
                {"Param", "3"}
            },
            new String [] {
                "Instruction Name", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        configTable.setOpaque(false);
        configTable.getTableHeader().setReorderingAllowed(false);
        panelConfig.setViewportView(configTable);
        if (configTable.getColumnModel().getColumnCount() > 0) {
            configTable.getColumnModel().getColumn(0).setResizable(false);
            configTable.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(panelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 240));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Disk size:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 274, 70, 20));

        txtDisk.setText("1024");
        getContentPane().add(txtDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 100, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Memory Size:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 100, 20));

        txtMemory.setText("128");
        getContentPane().add(txtMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 80, 20));

        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 400, 50));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -6, 480, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        for(int i = 0;i<configTable.getRowCount();i++){
                int number = Integer.parseInt(configTable.getModel().getValueAt(i,1).toString());
                Instruction ins = new Instruction(configTable.getModel().getValueAt(i,0).toString(),number);
                config.add(ins);
        }
        if (Integer.parseInt(txtMemory.getText()) <= 128 && Integer.parseInt(txtDisk.getText()) <= 1024){
            main window = new main(config,Integer.parseInt(txtMemory.getText()),Integer.parseInt(txtDisk.getText()));
            window.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Check your memory or disk size settings. Out of range.");
        }
        
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnStart;
    private javax.swing.JTable configTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane panelConfig;
    private javax.swing.JTextField txtDisk;
    private javax.swing.JTextField txtMemory;
    // End of variables declaration//GEN-END:variables
}
